"""Build a complete executed-style project report notebook from artifacts.

The notebook is generated after experiments so that figures, tables, citations,
and code references are synchronized with the actual run.
"""

from __future__ import annotations

from pathlib import Path
import json
import textwrap

import nbformat as nbf
import pandas as pd


REPORT_PATH = Path("notebooks/Adaptive_Inventory_Pricing_Tabular_RL_Report.ipynb")


def markdown(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(textwrap.dedent(text).strip())


def code(source: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(textwrap.dedent(source).strip())


def table_md(df: pd.DataFrame, max_rows: int = 12) -> str:
    return df.head(max_rows).to_markdown(index=False)


def main() -> None:
    reports = Path("reports")
    tables = reports / "tables"
    figures = reports / "figures"
    summary = json.loads((reports / "experiment_summary.json").read_text(encoding="utf-8"))
    eval_summary = pd.read_csv(tables / "evaluation_summary.csv")
    tuning = pd.read_csv(tables / "hyperparameter_tuning_results.csv")
    sales_split = pd.read_csv(tables / "sales_by_split.csv")
    preview = pd.read_csv(tables / "selected_series_preview.csv")
    sensitivity_path = tables / "sensitivity_analysis.csv"
    sensitivity = pd.read_csv(sensitivity_path) if sensitivity_path.exists() else pd.DataFrame()

    best_policy = eval_summary.sort_values("return_mean", ascending=False).iloc[0]
    meta = summary["metadata"]
    env = summary["environment_config"]

    nb = nbf.v4.new_notebook()
    nb["metadata"]["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
    nb["metadata"]["language_info"] = {"name": "python", "version": "3.11"}

    cells = [
        markdown(
            f"""
            # Adaptive Inventory & Pricing with Tabular Reinforcement Learning

            **Group Project 13**  
            **Members:** Jiayi Zhuo, Keyang Li, Rongze Gao, Zhexi Wang  
            **Course:** BU.520.750.51.SP26  

            This notebook is the complete technical report for the project. It documents the motivation,
            data-processing pipeline, finite MDP design, tabular RL methods, hyperparameter tuning,
            baseline comparison, and final empirical analysis. All reported results are generated by
            the repository scripts and saved under `reports/`.
            """
        ),
        markdown(
            """
            ## 1. Research Context and Literature

            The project studies joint retail pricing and replenishment as a sequential decision problem.
            This framing is motivated by classical reinforcement learning, where an agent learns a policy
            through interaction with a Markov Decision Process (Sutton & Barto, 2018). Q-learning is a
            model-free temporal-difference method for learning action values in controlled Markovian
            domains (Watkins & Dayan, 1992), while SARSA provides an on-policy temporal-difference
            alternative that evaluates the behavior policy under exploration (Rummery & Niranjan, 1994;
            Sutton & Barto, 2018).

            The retail data foundation is the M5 Forecasting Accuracy dataset. The M5 competition used
            Walmart unit-sales data with daily product-store observations, sell prices, and calendar
            information, making it a credible source for demand calibration (Makridakis et al., 2022;
            Kaggle, 2024; Zenodo, 2024). Because M5 does not include true on-hand inventory or lost
            demand, this project uses M5 to calibrate demand and builds an explicit simulator for
            replenishment, holding cost, stockout cost, and price response. This choice is consistent with
            the operations literature, where inventory control is commonly represented as an MDP with
            ordering, holding, and shortage costs (Gijsbrechts et al., 2022; Mahajan, n.d.; NEASQC, 2024).
            Dynamic pricing studies similarly motivate reinforcement learning because prices influence
            future demand and revenue trajectories rather than only one-period outcomes (Apte et al.,
            2024).
            """
        ),
        markdown(
            f"""
            ## 2. Data Source and Selected SKU

            The experiment selected one M5 product-store time series:

            - Item: `{meta['item_id']}`
            - Store: `{meta['store_id']}`
            - State: `{meta['state_id']}`
            - Department/category: `{meta['dept_id']}` / `{meta['cat_id']}`
            - Mean daily sales: `{meta['mean_sales']:.3f}`
            - Nonzero-sales ratio: `{meta['nonzero_ratio']:.3f}`
            - Median sell price: `${meta['median_price']:.2f}`
            - Price coefficient of variation: `{meta['price_cv']:.3f}`

            The preprocessing script chooses a series with enough nonzero demand and nontrivial price
            information so that the simulator does not collapse into a degenerate "never order" problem.
            The chronological split preserves time order: train data calibrates demand, validation data
            tunes hyperparameters, and test episodes evaluate final policies.
            """
        ),
        code(
            """
            import json
            from pathlib import Path
            import pandas as pd
            import matplotlib.pyplot as plt

            reports = Path('../reports') if Path('../reports').exists() else Path('reports')
            tables = reports / 'tables'
            figures = reports / 'figures'

            sales_by_split = pd.read_csv(tables / 'sales_by_split.csv')
            preview = pd.read_csv(tables / 'selected_series_preview.csv')
            evaluation_summary = pd.read_csv(tables / 'evaluation_summary.csv')
            tuning_results = pd.read_csv(tables / 'hyperparameter_tuning_results.csv')
            training_history = pd.read_csv(tables / 'training_history.csv')
            evaluation_episodes = pd.read_csv(tables / 'evaluation_episodes.csv')
            sales_by_split
            """
        ),
        markdown("### Split-level Sales Summary\n\n" + table_md(sales_split)),
        markdown("### Processed Series Preview\n\n" + table_md(preview)),
        markdown("### Data Overview Figure\n\n![Data overview](../reports/figures/data_overview.png)"),
        markdown(
            f"""
            ## 3. MDP Design

            The environment is a finite MDP with `{summary['n_states']}` states and `{summary['n_actions']}`
            actions, for `{summary['state_action_values']}` tabular state-action values. This is intentionally
            small enough for tabular RL and large enough to represent the core operational tradeoffs.

            The state is:

            `s_t = (inventory_bin, demand_signal_bin, price_tier, calendar_type, pipeline_bin)`

            Inventory is discretized into stockout, low, medium, high, and excess. Demand signal is based
            on lagged seven-day rolling demand and discretized into low, normal, and high. Price tier is
            discount, regular, or premium. Calendar type distinguishes weekday, weekend, and event/SNAP
            contexts. Pipeline inventory records whether replenishment is already arriving soon.

            The action is:

            `a_t = (price_choice, order_quantity)`

            Price choices are discount, regular, and premium. Order choices are none, small, medium, and
            large. The selected simulator parameters are:

            - Capacity: `{env['capacity']}` units
            - Lead time: `{env['lead_time']}` days
            - Order quantities: `{env['order_quantities']}`
            - Discount price multiplier: `{env['discount_multiplier']}`
            - Premium price multiplier: `{env['premium_multiplier']}`
            - Discount demand lift: `{env['discount_demand_lift']}`
            - Premium demand drop: `{env['premium_demand_drop']}`

            The reward is daily operating profit: sales revenue minus procurement cost, fixed ordering
            cost, holding cost, stockout penalty, excess-inventory penalty, and price-change penalty.
            This reward avoids the common mistake of optimizing revenue alone, which can over-discount
            or over-order, and also avoids a service-insensitive profit objective by penalizing lost sales.
            """
        ),
        markdown(
            """
            ## 4. Training and Hyperparameter Optimization

            The project compares tabular Q-learning and tabular SARSA. A grid search was run over learning
            rate, discount factor, epsilon decay, and minimum epsilon. Each configuration was trained across
            multiple seeds and evaluated on validation episodes. The best configuration for each algorithm
            was then retrained for the final training budget and evaluated on held-out test episodes.

            This validation-first design prevents selecting hyperparameters using the final test results.
            """
        ),
        markdown("### Top Hyperparameter Configurations\n\n" + table_md(tuning.head(10))),
        markdown("### Training Curve\n\n![Training curve](../reports/figures/training_curve.png)"),
        code(
            """
            training_history.groupby('algorithm')['return'].agg(['count', 'mean', 'std', 'min', 'max']).round(3)
            """
        ),
        markdown(
            """
            ## 5. Baselines

            The learned policies are compared against four interpretable baselines:

            1. **Random valid action**, a lower-bound sanity check.
            2. **Static regular price + reorder point**, a standard inventory-control heuristic.
            3. **Regular + average demand order-up-to**, a demand-planning baseline.
            4. **Inventory markdown heuristic**, which discounts high inventory and raises price under scarcity.

            These baselines make the comparison stronger than only showing that RL beats random behavior.
            """
        ),
        markdown("## 6. Test Evaluation Results\n\n" + table_md(eval_summary, max_rows=20)),
        markdown("### Test Return Comparison\n\n![Evaluation returns](../reports/figures/evaluation_returns.png)"),
        markdown("### Operational Metrics\n\n![Operational metrics](../reports/figures/evaluation_operational_metrics.png)"),
        markdown(
            f"""
            The best average test return was achieved by **{best_policy['policy']}** with a mean cumulative
            reward of `{best_policy['return_mean']:.2f}` and a mean fill rate of
            `{best_policy['fill_rate_mean']:.3f}`. The fill-rate metric is important because a policy can
            increase short-term profit by avoiding inventory, but that behavior would create stockouts and
            poor service. The combined profit and service analysis therefore gives a more complete view of
            policy quality.
            """
        ),
        code(
            """
            evaluation_episodes.groupby('policy')[['return', 'fill_rate', 'stockout_units', 'avg_inventory']].describe().round(3)
            """
        ),
        markdown("## 7. Learned Policy Interpretation\n\n![Q-learning policy heatmap](../reports/figures/q_learning_policy_heatmap.png)\n\n![SARSA policy heatmap](../reports/figures/sarsa_policy_heatmap.png)"),
        markdown(
            """
            The policy heatmaps show one interpretable slice of the learned policy: weekday, regular current
            price, and no pipeline inventory. The table annotations reveal how the action changes as
            inventory and demand signal move from low to high. This is the main advantage of keeping the
            project tabular: the final policy can be inspected directly rather than treated as a black box.
            """
        ),
        markdown(
            """
            ## 8. Limitations and Sensitivity

            The experiment makes explicit assumptions because public M5 data does not report inventory,
            replenishment orders, or lost demand. Observed sales may be censored by historical stockouts,
            and historical prices are observational rather than randomized. For that reason, the project
            should be interpreted as a tabular RL simulator calibrated by real retail data, not as a causal
            estimate of Walmart's true pricing response.

            We therefore evaluate sensitivity to price elasticity, lead time, holding cost, and stockout
            penalty. In this analysis, the learned Q-tables are kept fixed and evaluated under perturbed
            simulator assumptions. This does not replace retraining under each scenario, but it reveals how
            robust the learned policies are when the operating assumptions change.
            """
        ),
        markdown(
            ("### Sensitivity Results\n\n" + table_md(sensitivity, max_rows=20))
            if not sensitivity.empty
            else "### Sensitivity Results\n\nSensitivity analysis has not been generated yet."
        ),
        markdown("![Sensitivity returns](../reports/figures/sensitivity_returns.png)" if not sensitivity.empty else ""),
        markdown(
            """
            ## 9. Reproducibility

            Main commands:

            ```powershell
            python scripts/download_m5.py
            python scripts/run_experiments.py --tuning-episodes 600 --final-episodes 3000 --evaluation-episodes 120
            python scripts/build_report_notebook.py
            pytest
            ```

            CI uses a synthetic smoke dataset to keep GitHub Actions fast and independent of the external
            M5 download. The full local report uses the real M5-derived processed subset.
            """
        ),
        markdown(
            """
            ## References

            Apte, M., Kale, K., Datar, P., & Deshmukh, P. (2024). *Dynamic retail pricing via Q-learning:
            A reinforcement learning framework for enhanced revenue management*. arXiv.
            https://arxiv.org/abs/2411.18261

            Gijsbrechts, J., Boute, R. N., Van Mieghem, J. A., & Zhang, D. (2022). Deep reinforcement
            learning for inventory control: A roadmap. *European Journal of Operational Research, 298*(2),
            401-412. https://doi.org/10.1016/j.ejor.2021.07.016

            Kaggle. (2024). *M5 Forecasting - Accuracy*. https://www.kaggle.com/competitions/m5-forecasting-accuracy/data

            Mahajan, A. (n.d.). *Inventory management revisited*. https://adityam.github.io/stochastic-control/mdps/inventory-management-revisited.html

            Makridakis, S., Spiliotis, E., & Assimakopoulos, V. (2022). The M5 competition: Background,
            organization, and implementation. *International Journal of Forecasting, 38*(4), 1325-1336.
            https://doi.org/10.1016/j.ijforecast.2021.07.007

            NEASQC. (2024). *Reinforcement learning for inventory management*.
            https://www.neasqc.eu/use-case/reinforcement-learning-for-inventory-management/

            Rummery, G. A., & Niranjan, M. (1994). *On-line Q-learning using connectionist systems*
            (Technical Report CUED/F-INFENG/TR 166). Cambridge University Engineering Department.

            Sutton, R. S., & Barto, A. G. (2018). *Reinforcement learning: An introduction* (2nd ed.).
            MIT Press.

            Watkins, C. J. C. H., & Dayan, P. (1992). Q-learning. *Machine Learning, 8*, 279-292.
            https://doi.org/10.1007/BF00992698

            Zenodo. (2024). *M5 Forecasting Accuracy dataset* (Version v1) [Data set].
            https://doi.org/10.5281/zenodo.12636070
            """
        ),
    ]
    nb["cells"] = cells
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, REPORT_PATH)
    print(f"Wrote {REPORT_PATH.resolve()}")


if __name__ == "__main__":
    main()
